/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_4ACCBAA__
#define __PLUGINEDITOR_H_4ACCBAA__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "EarOSCServer.h"
#include "PadGrid.h"


//==============================================================================
/** This is the editor component that our filter will display.
*/
class TheEarPluginAudioProcessorEditor  : public AudioProcessorEditor,
                                            public SliderListener,
                                            public Timer,
                                            public Button::Listener,
                                            public ChangeListener
{
public:
    TheEarPluginAudioProcessorEditor (TheEarPluginAudioProcessor&);
    ~TheEarPluginAudioProcessorEditor();

    //==============================================================================
    void timerCallback() override;
    void paint (Graphics&) override;
    void resized() override;
    void sliderValueChanged (Slider*) override;
    void sliderDragStarted  (Slider*) override;
    void sliderDragEnded    (Slider*) override;
    void buttonClicked(Button* button) override;
    void changeListenerCallback (ChangeBroadcaster *source);

private:
    MidiKeyboardComponent midiKeyboard;
    Label infoLabel, gainLabel, delayLabel;
    Slider gainSlider, delaySlider;
    ScopedPointer<ResizableCornerComponent> resizer;
    ComponentBoundsConstrainer resizeLimits;
    EarOSCServer earOSCServer;
    
    TextButton resetSynthButton;
    Label currentKeyScaleLabel, liveKeyScaleLabel;
    TextEditor currentKeyScaleTextBox, liveKeyScaleTextBox;

    AudioPlayHead::CurrentPositionInfo lastDisplayedPosition;

    //==============================================================================
    TheEarPluginAudioProcessor& getProcessor() const
    {
        return static_cast<TheEarPluginAudioProcessor&> (processor);
    }

    AudioProcessorParameter* getParameterFromSlider (const Slider*) const;

    void displayPositionInfo (const AudioPlayHead::CurrentPositionInfo& pos);
    
    Array<File> getAudioFiles(const File& audioFolder, String key, String scale);
    
    PadGrid padGrid;
};


#endif  // __PLUGINEDITOR_H_4ACCBAA__
