/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_4ACCBAA__
#define __PLUGINEDITOR_H_4ACCBAA__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "EarOSCServer.h"
#include "PadGrid.h"
#include "InterfaceComponent.h"
#include "DataComponent.h"

//==============================================================================
class MainTab  : public TabbedComponent
{
public:
    MainTab (MidiKeyboardState& s, AudioProcessor& p)
    : TabbedComponent (TabbedButtonBar::TabsAtTop)
    {
        addTab ("Interface",  Colours::grey, new InterfaceComponent(s, p), true);
        addTab ("Data",  Colours::grey, new DataComponent(), true);
    }
};


//==============================================================================
/** This is the editor component that our filter will display.
*/
class TheEarPluginAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    TheEarPluginAudioProcessorEditor (TheEarPluginAudioProcessor&);
    ~TheEarPluginAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:
    MainTab mainTab;
};


#endif  // __PLUGINEDITOR_H_4ACCBAA__
