/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
TheEarPluginAudioProcessorEditor::TheEarPluginAudioProcessorEditor (TheEarPluginAudioProcessor& owner)
    : AudioProcessorEditor (owner),
    mainTab(owner.keyboardState, processor)


{
    addAndMakeVisible(mainTab);
    setSize(1024, 768);
}

TheEarPluginAudioProcessorEditor::~TheEarPluginAudioProcessorEditor()
{
}


//==============================================================================
void TheEarPluginAudioProcessorEditor::paint (Graphics& g)
{
    g.setGradientFill (ColourGradient (Colours::white, 0, 0,
                                       Colours::grey, 0, (float) getHeight(), false));
    
    g.fillAll();
}

void TheEarPluginAudioProcessorEditor::resized()
{


    mainTab.setBounds(getLocalBounds());
    
}


